version: 1.0.0

global:
  default_update_interval: 24h

providers:
  - id: example_provider
    name: "Example Provider"
    enabled: false
    module: example_provider.py
    update_interval: 1h
    region: berlin

  - id: echtzeitmusik
    name: "Echtzeitmusik"
    enabled: true
    module: echtzeitmusik_provider.py
    update_interval: 6h
    region: berlin
    address: "Berlin"
    latitude: 52.52437
    longitude: 13.41053

  - id: brotfabrik
    name: "Brotfabrik Berlin"
    enabled: true
    module: brotfabrik_provider.py
    update_interval: 6h
    region: berlin
    address: "Brotfabrik Berlin, Caligariplatz 1, 13086 Berlin"
    latitude: 52.5518
    longitude: 13.4357

  - id: theater_im_delphi
    name: "Theater im Delphi"
    enabled: true
    module: theater_im_delphi_provider.py
    update_interval: 24h
    region: berlin
    address: "Gustav-Adolf-Straße 2, 13086 Berlin"
    latitude: 52.551694
    longitude: 13.431111

  - id: kino_toni
    name: "Kino Toni"
    enabled: true
    module: kino_toni_provider.py
    update_interval: 24h
    region: berlin
    address: "Antonplatz 1, 13086 Berlin"
    latitude: 52.5488
    longitude: 13.4509

  - id: peter_edel
    name: "Bildungs- und Kulturzentrum Peter Edel"
    enabled: true
    module: peter_edel_provider.py
    update_interval: 24h
    region: berlin
    address: "Berliner Allee 125, 13088 Berlin"
    latitude: 52.5509
    longitude: 13.4618

  - id: sexauer
    name: "Sexauer Gallery"
    enabled: true
    module: sexauer_provider.py
    update_interval: 24h
    region: berlin
    address: "Streustraße 90, 13086 Berlin"
    latitude: 52.5509
    longitude: 13.4394

  - id: kh_berlin
    name: "Weißensee Kunsthochschule Berlin"
    enabled: true
    module: kh_berlin_provider.py
    update_interval: 24h
    region: berlin
    address: "Bühringstraße 20, 13086 Berlin"
    latitude: 52.5577
    longitude: 13.4387

  - id: park_klinik_weissensee
    name: "Park-Klinik Weißensee"
    enabled: true
    module: park_klinik_weissensee_provider.py
    update_interval: 24h
    region: berlin
    address: "Schönstraße 80, 13086 Berlin"
    latitude: 52.5577
    longitude: 13.4515

  - id: frei_zeit_haus
    name: "Frei-Zeit-Haus"
    enabled: true
    module: frei_zeit_haus_provider.py
    update_interval: 24h
    region: berlin
    address: "Pistoriusstraße 23, 13086 Berlin"
    latitude: 52.5542
    longitude: 13.4503

  - id: schaubude_berlin
    name: Schaubude Berlin
    enabled: true
    module: schaubude_berlin_provider.py
    update_interval: 24h
    region: Berlin
    address: Greifswalder Str. 81-84, 10405 Berlin
    latitude: 52.5408
    longitude: 13.4328

  - id: kollage_kollectiv
    name: Kollage Kollectiv
    enabled: true
    module: kollage_kollectiv_provider.py
    update_interval: 24h
    region: Berlin
    address: Lilli-Henoch-Straße 21, 10405 Berlin
    latitude: 52.5358
    longitude: 13.4312

  - id: zirkus_mond
    name: Zirkus Mond
    enabled: true
    module: zirkus_mond_provider.py
    update_interval: 24h
    region: Berlin
    address: Lilli-Henoch-Straße, 10405 Berlin
    latitude: 52.5358
    longitude: 13.4312

  - id: planetarium_berlin
    name: Stiftung Planetarium Berlin
    enabled: true
    module: planetarium_berlin_provider.py
    update_interval: 24h
    region: Berlin

