version: 1.0.0

global:
  default_update_interval: 24h

providers:
  - id: example_provider
    name: "Example Provider"
    enabled: false
    module: example_provider.py
    update_interval: 1h
    region: berlin

  - id: echtzeitmusik
    name: "Echtzeitmusik"
    enabled: true
    module: echtzeitmusik_provider.py
    update_interval: 6h
    region: berlin
    address: "Berlin"
    latitude: 52.52437
    longitude: 13.41053

  - id: brotfabrik
    name: "Brotfabrik Berlin"
    enabled: true
    module: brotfabrik_provider.py
    update_interval: 6h
    region: berlin
    address: "Brotfabrik Berlin, Caligariplatz 1, 13086 Berlin"
    latitude: 52.5518
    longitude: 13.4357

  - id: theater_im_delphi
    name: "Theater im Delphi"
    enabled: true
    module: theater_im_delphi_provider.py
    update_interval: 24h
    region: berlin
    address: "Gustav-Adolf-Straße 2, 13086 Berlin"
    latitude: 52.551694
    longitude: 13.431111

  - id: kino_toni
    name: "Kino Toni"
    enabled: true
    module: kino_toni_provider.py
    update_interval: 24h
    region: berlin
    address: "Antonplatz 1, 13086 Berlin"
    latitude: 52.5488
    longitude: 13.4509

  - id: peter_edel
    name: "Bildungs- und Kulturzentrum Peter Edel"
    enabled: true
    module: peter_edel_provider.py
    update_interval: 24h
    region: berlin
    address: "Berliner Allee 125, 13088 Berlin"
    latitude: 52.5509
    longitude: 13.4618

  - id: sexauer
    name: "Sexauer Gallery"
    enabled: true
    module: sexauer_provider.py
    update_interval: 24h
    region: berlin
    address: "Streustraße 90, 13086 Berlin"
    latitude: 52.5509
    longitude: 13.4394

  - id: kh_berlin
    name: "Weißensee Kunsthochschule Berlin"
    enabled: true
    module: kh_berlin_provider.py
    update_interval: 24h
    region: berlin
    address: "Bühringstraße 20, 13086 Berlin"
    latitude: 52.5577
    longitude: 13.4387
