version: 1.0.0

global:
  default_update_interval: 24h

providers:
  - id: example_provider
    name: "Example Provider"
    enabled: false
    module: example_provider.py
    update_interval: 1h
    region: berlin

  - id: echtzeitmusik
    name: "Echtzeitmusik"
    enabled: true
    module: echtzeitmusik_provider.py
    update_interval: 6h
    region: berlin
    address: "Berlin"
    latitude: 52.52437
    longitude: 13.41053

  - id: brotfabrik
    name: "Brotfabrik Berlin"
    enabled: true
    module: brotfabrik_provider.py
    update_interval: 6h
    region: berlin
    address: "Brotfabrik Berlin, Caligariplatz 1, 13086 Berlin"
    latitude: 52.5518
    longitude: 13.4357

  - id: theater_im_delphi
    name: "Theater im Delphi"
    enabled: true
    module: theater_im_delphi_provider.py
    update_interval: 24h
    region: berlin
    address: "Gustav-Adolf-Straße 2, 13086 Berlin"
    latitude: 52.551694
    longitude: 13.431111

  - id: kino_toni
    name: "Kino Toni"
    enabled: true
    module: kino_toni_provider.py
    update_interval: 24h
    region: berlin
    address: "Antonplatz 1, 13086 Berlin"
    latitude: 52.5488
    longitude: 13.4509

  - id: peter_edel
    name: "Bildungs- und Kulturzentrum Peter Edel"
    enabled: true
    module: peter_edel_provider.py
    update_interval: 24h
    region: berlin
    address: "Berliner Allee 125, 13088 Berlin"
    latitude: 52.5509
    longitude: 13.4618

  - id: sexauer
    name: "Sexauer Gallery"
    enabled: true
    module: sexauer_provider.py
    update_interval: 24h
    region: berlin
    address: "Streustraße 90, 13086 Berlin"
    latitude: 52.5509
    longitude: 13.4394

  - id: kh_berlin
    name: "Weißensee Kunsthochschule Berlin"
    enabled: true
    module: kh_berlin_provider.py
    update_interval: 24h
    region: berlin
    address: "Bühringstraße 20, 13086 Berlin"
    latitude: 52.5577
    longitude: 13.4387

  - id: park_klinik_weissensee
    name: "Park-Klinik Weißensee"
    enabled: true
    module: park_klinik_weissensee_provider.py
    update_interval: 24h
    region: berlin
    address: "Schönstraße 80, 13086 Berlin"
    latitude: 52.5577
    longitude: 13.4515

  - id: frei_zeit_haus
    name: "Frei-Zeit-Haus"
    enabled: true
    module: frei_zeit_haus_provider.py
    update_interval: 24h
    region: berlin
    address: "Pistoriusstraße 23, 13086 Berlin"
    latitude: 52.5542
    longitude: 13.4503

  - id: schaubude_berlin
    name: Schaubude Berlin
    enabled: true
    module: schaubude_berlin_provider.py
    update_interval: 24h
    region: Berlin
    address: Greifswalder Str. 81-84, 10405 Berlin
    latitude: 52.5408
    longitude: 13.4328

  - id: kollage_kollectiv
    name: Kollage Kollectiv
    enabled: true
    module: kollage_kollectiv_provider.py
    update_interval: 24h
    region: Berlin
    address: Lilli-Henoch-Straße 21, 10405 Berlin
    latitude: 52.5358
    longitude: 13.4312

  - id: zirkus_mond
    name: Zirkus Mond
    enabled: true
    module: zirkus_mond_provider.py
    update_interval: 24h
    region: Berlin
    address: Lilli-Henoch-Straße, 10405 Berlin
    latitude: 52.5358
    longitude: 13.4312

  - id: gruene_pankow
    name: "Grüne Pankow"
    enabled: true
    module: gruene_pankow_provider.py
    update_interval: 12h
    region: berlin
    latitude: 52.567
    longitude: 13.4122

  - id: kino_krokodil
    name: "Kino Krokodil"
    enabled: true
    module: kino_krokodil_provider.py
    update_interval: 12h
    region: berlin
    address: "Greifenhagener Str. 32, 10437 Berlin"
    latitude: 52.5497
    longitude: 13.4182

  - id: buehnenrausch
    name: "BühnenRausch"
    enabled: true
    module: buehnenrausch_provider.py
    update_interval: 12h
    region: berlin
    address: "Erich-Weinert-Str. 27, 10439 Berlin"
    latitude: 52.5501
    longitude: 13.4140

  - id: freilichtbuehne_weissensee
    name: "Freilichtbühne Weißensee"
    enabled: true
    module: freilichtbuehne_weissensee_provider.py
    update_interval: 12h
    region: berlin
    address: "Große Seestraße 10, 13086 Berlin"
    latitude: 52.5540
    longitude: 13.4630

  - id: velodrom
    name: "Velodrom"
    enabled: true
    module: velodrom_provider.py
    update_interval: 12h
    region: berlin
    address: "Paul-Heyse-Straße 26, 10407 Berlin"
    latitude: 52.5302
    longitude: 13.4504

  - id: ausland
    name: "ausland"
    enabled: true
    module: ausland_provider.py
    update_interval: 12h
    region: berlin
    address: "Lychener Str. 60, 10437 Berlin"
    latitude: 52.5418
    longitude: 13.4216

  - id: party_in_pankow
    name: "Party in Pankow"
    enabled: true
    module: party_in_pankow_provider.py
    update_interval: 12h
    region: berlin
    address: "Raumerstraße 39, 10437 Berlin"
    latitude: 52.5445
    longitude: 13.4212

  - id: kunstfabrik_schlot
    name: "Kunstfabrik Schlot"
    enabled: true
    module: kunstfabrik_schlot_provider.py
    update_interval: 12h
    region: berlin
    address: "Invalidenstraße 117, 10115 Berlin"
    latitude: 52.5308
    longitude: 13.3833

  - id: planetarium_berlin
    name: Stiftung Planetarium Berlin
    enabled: true
    module: planetarium_berlin_provider.py
    update_interval: 24h
    region: Berlin

