services:
  # The App
  salon-server:
    # REPLACE <your-username> AND <repo-name> WITH YOUR GITHUB USERNAME AND REPO NAME (LOWERCASE)
    # Example: ghcr.io/hartkens/salondergedankenserver:latest
    image: ghcr.io/<your-username>/<repo-name>:latest
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: "your-domain.com"
      caddy.reverse_proxy: "{{upstreams 8000}}"
    environment:
      # Add any environment variables your app needs here
      - TZ=Europe/Berlin

  # Automatic HTTPS Proxy
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  # Auto-Updater
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup # Check every 5 minutes, remove old images
    environment:
      - REPO_USER=${GITHUB_USER}
      - REPO_PASS=${GITHUB_TOKEN}

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
